### ISSUE TITLE
error: Html.playground:30:10: error: type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by finestructure** [pointfreeco/swift-html#10]
I've come across this error running the included playground:

```
error: Html.playground:30:10: error: type of expression is ambiguous without more context
    head([
```

This is on swift-4.2 but the playground also fails in 4.1.2 for me (although I believe it was a different error message).

The issue is that in in the section

```
let doc = html([
    head([
        style(stylesheet)
        ]),
```

`stylesheet` is a `String` after assignment while `style` has the signature

```
public func style(_ content: StaticString) -> ChildOf<Tag.Head> {
```

This is fixable by either declaring

```
let stylesheet = style("""
...
```

and using

```
let doc = html([
    head([
        stylesheet
        ]),
```

or changing `style` to 

```
public func style(_ content: String) -> ChildOf<Tag.Head> {
```

The latter seems to be the more lenient variant but I'm wondering if there was a deeper reason to constrain it to StaticString?

**Comment by stephencelis** [comment]
Ah, there's a version of `style` that takes an `unsafe: String` parameter. We'll update the playground accordingly, thanks!
