### ISSUE TITLE
Snapshot Testing Version Mixmatch

### ISSUE THREAD

**Issue by nonfungibletunji** [pointfreeco/swift-html#103]
error: the library 'HtmlSnapshotTesting' requires macos 10.13, but depends on the product 'SnapshotTesting' which requires macos 10.15; consider changing the library 'HtmlSnapshotTesting' to require macos 10.15 or later, or the product 'SnapshotTesting' to require macos 10.13 or earlier.

**Comment by lukesutton** [comment]
I'm also seeing this same issue on MacOS Sonoma. Specifically when using swift-html-vapor v0.4.0.

**Comment by ferologics** [comment]
for anyone running into this you can depend on the `main` branch and set your package's platform target to `v10_15`
```
// swift-tools-version:5.9

import PackageDescription

let package = Package(
  name: "foo",
  platforms: [ .macOS(.v10_15), ], // 👈
  dependencies: [
    .package(url: "https://github.com/pointfreeco/swift-html", branch: "main"),  // 👈
  ],
  targets: [
    .target(
      name: "web",
      dependencies: [
        .product(name: "Html", package: "swift-html"),
      ],
      path: "Sources/foo/"
    )
  ]
)
```
