### ISSUE TITLE
Style attribute function does not allow runtime strings

### ISSUE THREAD

**Issue by turbolent** [pointfreeco/swift-html#12]
Is there any particular reason why the `style` attribute function only allows static strings? (see https://github.com/pointfreeco/swift-html/blob/f4ac5ec066c53d942fb79dc00bfbb523503131e1/Sources/Html/Attributes.swift#L1117)

I used the old `Html` module from `swift-web` before and it didn't use to have this limitation.

**Comment by stephencelis** [comment]
Hi there! We've renamed the version that takes any old string `style(unsafe:)`, denoting that this string may be unsafe from user input. All elements that take CSS or JavaScript have `StaticString` and `unsafe: String` versions.

**Comment by stephencelis** [comment]
Whoops! I guess we have those overloads for `element` but not `attribute`. Will be adding shortly!
