### ISSUE TITLE
Playground: No such module 'Html'

### ISSUE THREAD

**Issue by BryanJBryce** [pointfreeco/swift-html#16]
Html Playground doesn't run, it can't find the Html module.

**Comment by stephencelis** [comment]
@BryanJBryce Playgrounds are a bit tricky in that they require you build the module first. Can you build the framework for macOS and try again? Might require closing/reopening the workspace after building.

**Comment by BryanJBryce** [comment]
@stephencelis Sorry, I'm not familiar with this type of Xcode project setup. Here's a picture of what I see when I open `HTML.xcworkspace`. I don't see anywhere to build anything. 
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/1293064/49031470-42d54a00-f167-11e8-89af-fb0af9e3ff26.png">

**Comment by stephencelis** [comment]
@BryanJBryce I got an email notification update for this thread but am not seeing the comment. Can you pull down the latest and try again? Running the project file previously required running `make xcodeproj`, but we've now checked in the project file explicitly, which should mean that you can build targets just fine automatically!

**Comment by BryanJBryce** [comment]
@stephencelis Just tried that and it that fixed it, thank you.

**Comment by stephencelis** [comment]
🙌
