### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by zoul** [pointfreeco/swift-html#17]
Until Carthage gets SPM support (https://github.com/Carthage/Carthage/pull/1945), would you consider accepting a PR that would add an Xcode project to build the library? To improve Xcode support out of the box.

**Comment by zoul** [comment]
I’m an idiot and I have overlooked the existing Xcode workspace. But if I understand things correctly, you still rely on the one extra step to generate the Xcode project from SPM, so the library cannot be used directly by Carthage:

```bash
*** Skipped building swift-html due to the error:
Dependency "swift-html" has no shared framework schemes
```

I understand that checking auto-generated files into the repo has its downsides, but doing it at least until Carthage’s SPM support improves would be a nice step towards the users of this library. What do you think?

**Comment by stephencelis** [comment]
Hi @zoul! We'd love to support Carthage and plan on getting around to it by using [XcodeGen](https://github.com/yonaskolb/XcodeGen). We've already done this in our [SnapshotTesting](https://github.com/pointfreeco/swift-snapshot-testing) library with this configuration file:

https://github.com/pointfreeco/swift-snapshot-testing/blob/master/project.yml

Would you be up for giving it a shot?

**Comment by zoul** [comment]
🎉, splendid. I see that the SnapshotTesting project builds out of the box using Carthage, great. XcodeGen looks like it’s meant to generate the Xcode project files on the fly, so now I am confused. Is the idea to use XcodeGen to generate the Xcode project, _but_ check that into the repo? If so, why is XcodeGen needed instead of SPM’s `generate-xcodeproj`? If you can unconfuse me a bit, I would be thrilled to take a shot.

**Comment by stephencelis** [comment]
SPM's project file format is unfortunately incompatible with Carthage since Carthage requires separate framework targets per platform. So yep! The idea would be to use XcodeGen to generate a Carthage-compatible project file and check it directly into the repository.

**Comment by zoul** [comment]
Splendid². It’s now evening here, I will take a look at it in about 12 hours. Thank you!

**Comment by stephencelis** [comment]
No rush! It might be some time before we get to it, so thanks so much for tackling it sooner!

**Comment by zoul** [comment]
> SPM's project file format is unfortunately incompatible with Carthage since Carthage requires separate framework targets per platform.

Does it? I have just [discovered the last week](https://davedelong.com/blog/2018/11/15/building-a-crossplatform-framework/) that I don’t need to create separate targets for each platform, and getting rid of the target-per-platform tomfoolery was a relief. Does the cross-platform framework throw Carthage off somewhere?

**Comment by stephencelis** [comment]
@zoul I unfortunately don't remember the details (I don't use Carthage), but we've had Carthage users periodically report bugs against universal framework project files we've used from SPM in the past.

**Comment by zoul** [comment]
With a bit of luck it could be just the project files generated by SPM. I would hate to convert my various frameworks to cross-platform only to revert it all because of bugs in Carthage. Let’s hope for a good SPM support in Xcode soon. Thank you!
