### ISSUE TITLE
"Type expression ambiguous" error

### ISSUE THREAD

**Issue by BryanJBryce** [pointfreeco/swift-html#21]
Whenever I use a variable for contents of `Node` I get compile error that says:
>Type of expression is ambiguous without more context

I'm unclear why this is the case and what I would need to do to fix it.
<img width="643" alt="image" src="https://user-images.githubusercontent.com/1293064/49045120-306e0700-f18d-11e8-8218-d8e1a921b674.png">

```
        guard let age: String = test.studentAgeAtTimeOfTest() else { return "error" }

        let htmlTree =
            html([
                head([

                    ]),
                body([
                    h1(["Student is \(age) years old"])
                    ])
                ])
```

**Comment by stephencelis** [comment]
Text nodes conform to `ExpressibleByStringLiteral`, but unfortunately `ExpressibleByStringInterpolation` was deprecated, so we can't fix this right now. You can use `.text` to explicitly build a text node:

``` swift
h1([.text("Student is \(age) years old")])
```

**Comment by BryanJBryce** [comment]
Thanks again!

**Comment by stephencelis** [comment]
Sorry for the inconvenience! Those error messages are definitely not great, though we don't have a ton of control there. We're taking note for future documentation :) This will also get better with Swift 5, where we can once again hook into a new string interpolation API.
