### ISSUE TITLE
Add support for nested lists

### ISSUE THREAD

**Issue by Gofake1** [pointfreeco/swift-html#32]
This should be valid but currently isn't:
```swift
ul([
  li(["1"]),
  li(["2"]),
  ul([
    li(["2a"]),
    li(["2b"])
  ])
])
```
I'm currently working around this by using the un-typechecked `element(...)` initializer.

**Comment by stephencelis** [comment]
Hi @Gofake1! I believe what you want is to nest the second `ul` inside an `li`. Nesting `ul` directly in a `ul` isn't valid HTML. You can verify using the W3 validator: https://validator.w3.org/nu/#textarea

In your case I think what you want is this:

``` swift
ul([
  li(["1"]),
  li([
    "2",
    ul([
      li(["2a"]),
      li(["2b"])
      ])
    ])
  ])
```

**Comment by Gofake1** [comment]
Ah, my bad.
