### ISSUE TITLE
(maybe-not-so-really) indirect enum Node

### ISSUE THREAD

**Issue by technicated** [pointfreeco/swift-html#36]
Hi guys! First of all, thank you for this great lib, you've done a great job with this and I love your work!

I was trying to kinda of rewrite your lib for fun in a playground and the compiler allowed me to declare the `Node` enum *without* marking the `.element` case as **indirect**. I wondered if that depends on the fact that *children* is actually an array of `Node`s and not a single `Node`... If that's the case you might want to drop the `indirect` modifier, too!

I don't even know if that might have benefit performance / memory wise, maybe the Swift compiler is smart enough and has never introduced the "indirect reference / pointer" to the node in question ever.

**Comment by stephencelis** [comment]
Ha, you're right! Array storage lets us avoid modifiers like `@escaping`, too, when storing a bunch of closures. I think `indirect` was necessary for an early revision of `Node`, and we've recently begun to explore another design which requires `indirect`, but this is still a good find and we'd be happy to drop the `indirect` in a PR in the meantime!

**Comment by technicated** [comment]
Here is the PR: https://github.com/pointfreeco/swift-html/pull/37

**Comment by stephencelis** [comment]
Closed by #37.
