### ISSUE TITLE
How to add colspan attribute to td

### ISSUE THREAD

**Issue by BryanJBryce** [pointfreeco/swift-html#44]
I'm trying to set the `colspan` attribute on a `td` element, but I'm getting an error:

`td([.colspan(2)], [.text(word.note)])`

**Comment by stephencelis** [comment]
Hi @BryanJBryce! Do you know if you're working off of a specific version or are you working off the `master` branch? If you have the specific commit, that'd be super helpful! Also, what error are you getting?

**Comment by stephencelis** [comment]
@BryanJBryce Any update here? Can you provide a full, failing example?
