### ISSUE TITLE
Roadmap? Swift 4, 5

### ISSUE THREAD

**Issue by marc-medley** [pointfreeco/swift-html#53]
I found version "0.3.0" did not run on a Swift 4.2.1 system. 

What is the plan relative to support/features for Swift 4 and Swift 5? Relative to the release numbers?

Is the 0.2.x Swift 4 version expected to have any new features and/or support updates?

Version differences? Or, maybe the version with Swift 5 so much better, that I should not prefer to spend too much time with the Swift 4 version??

Some roadmap-ish section would be generally helpful if the READMEmd.  Thanks.

**Comment by stephencelis** [comment]
Hi @marc-medley! Sorry for the churn. We definitely recommend upgrading to Swift 5 now that it's been officially released. Is anything preventing you from doing so or keeping you on Swift 4? We'd like to make upgrades a bit easier in the future, but hadn't anticipated folks being stuck on earlier versions of Swift.

Is it possible for you to point directly to this commit? https://github.com/pointfreeco/swift-html/commit/ac09f716dca4e941d340d712a39a519521042405

It contains the new APIs but doesn't require Swift 5 if you need more time to upgrade.

**Comment by marc-medley** [comment]
@stephencelis Xcode 10.2 which provides Swift 5 requires macOS Mojave. My mix of development machines includes hardware where macOS High Sierra is the last officially supported macOS. So, the need to upgrade to Mojave is the complicating factor, not the Swift 5 per se.

**Comment by stephencelis** [comment]
@marc-medley That makes sense, thanks! We'll look into how to best go about supporting multiple Swift versions in the future and try to get Swift 4 compatibility working again.

**Comment by marc-medley** [comment]
@stephencelis Ah, found [Swift 5.0 and XCode 10.1 – Using a Custom Toolchain](https://learningswift.brightdigit.com/swift-5-0-xcode-10-1/). I will look that this approach.

Still, the impact of the Swift 5 toolchain on a large set of Swift 4 projects here is TDB. Even if source compatibility is OK, a large pile of other details requiring attention can show up (e.g. deprecation warnings). 

For my use case, it would be ok to put the Swift 4 version on a branch with version 0.2.x release pattern for if/when any update(s) should occur. (_Unless the swift-html Swift 4 version is really conterproduction relative to where swift-html is heading.  Then this would be good to know too and not providing a Swift 4 version is also a valid option._)

Once swift-html decisions are reached relative to Swift 4 & 5, some general ([README](https://github.com/pointfreeco/swift-html/blob/master/README.md)) roadmap communication of which branch/version.pattern tracks to which Swift version and which support level (dev-new-features, lts-maintenance, not-supported) could also be helpful to others.

**Comment by marc-medley** [comment]
Well, apparently the Swift 5 tool chain with Xcode 10.1 has some non-trivial gotchas. 

First pass of [eval-vapor-leaf-stencil](https://github.com/VaporExamplesLab/eval-vapor-leaf-stencil) found serveral issues.  Including, `Html` does not link because "/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2019-03-26-a.xctoolchain/" does not include `lib/arc/libarclite_macosx.a`

![Swift5_StartingPoint](https://user-images.githubusercontent.com/15098151/55259796-e755be80-5223-11e9-8012-112ad6805e7f.png)

Also,

![Swift5Cannotconvert](https://user-images.githubusercontent.com/15098151/55259817-f63c7100-5223-11e9-96c8-01b612ac4805.png)

**Comment by stephencelis** [comment]
This should be fixed with the release of 0.3.1! Let us know if you have any more problems.

**Comment by marc-medley** [comment]
@stephencelis I did a quick check of `swift-html` v0.3.1 and found that the dependency `swift-snapshot-testing` is not Swift 4.2 compatible.  Reported as [swift-snapshot-testing issue #210](https://github.com/pointfreeco/swift-snapshot-testing/issues/210)

**Comment by stephencelis** [comment]
@marc-medley Thanks for reporting! We'll try to address in the next day or two.

**Comment by marc-medley** [comment]
@stephencelis Any news on _if/when_ [swift-snapshot-testing issue #210](https://github.com/pointfreeco/swift-snapshot-testing/issues/210) might be addressed so that swift-html might build with Swift 4.2?

**Comment by stephencelis** [comment]
Hey @marc-medley, sorry for the delay! This hasn't been an immediate issue that is blocking us, so we haven't addressed it yet. We'd definitely appreciate some help if you'd like to volunteer, though! Anything we can do to help get you started? The main issue seems to be building a release for both compiler versions using the appropriate directives. We'd certainly be thankful of any assistance in that department!
