### ISSUE TITLE
Ambiguous reference to member 'style'

### ISSUE THREAD

**Issue by BryanJBryce** [pointfreeco/swift-html#55]
![image](https://user-images.githubusercontent.com/1293064/58131124-b2863800-7bd2-11e9-9133-de63b4771696.png)

I'm sure this must be basic...but I'm not seeing why I get this error.

```
let htmlTree =
    Node.document(
        .html(
            .head(),
            .body(attributes: [.style(safe: "margin: 10px 35px 20px")], [.div(.text("Test"))])
        ))
```

**Comment by stephencelis** [comment]
@BryanJBryce In the screen shot it looks like you're using `.style("")` without the `safe:` label. Swift type checking has some problems without the labels, unfortunately, but `safe` and `unsafe` should disambiguate well.
