### ISSUE TITLE
HTML character entity incorrectly escaped

### ISSUE THREAD

**Issue by stephent** [pointfreeco/swift-html#57]
Maybe I'm doing this incorrectly, but it seems that if include an html entity such as &deg; (degrees), as follows

`
let div:Node = .div(
    .h3(.text("90&deg;"))
)
`

then the output in the rendered html document is `90&amp;deg;`.

Not sure if this is a bug or just me missing the correct method to include an character entity?

**Comment by stephent** [comment]
Ah, ok. I guess I should be using `.raw` instead of `.text`. Thanks!

**Comment by mbrandonw** [comment]
Hey Stephen! The `.text` case of the `Node` enum will always escape its contents, and so that is why you are seeing this extra escaping. If you want to bypass the escaping you can use the `.raw` case:

```
let div = Node.div(.h3(.raw("90&deg;")))
```

This type of node should of course be used with care since it does not do any escaping.

**Comment by mbrandonw** [comment]
Oh ha, we both commented at the same time. Glad you figured it out!

**Comment by stephent** [comment]
@mbrandonw thanks! One follow-up question - if I want to include something like `&deg;` in image alt text, what's the best way to handle that case?

**Comment by mbrandonw** [comment]
So `alt` attributes do not need to be escaped in HTML, you can even do things like:

```html
<img alt="<b>Hello</b>">
```

and the HTML tags will be apart the alternative text. There's no risk of accidental HTML injection either.

So for that attribute you can just use `°` directly.

**Comment by stephent** [comment]
Thanks again @mbrandonw . I suspect it's unrelated to html-swift, but when I use just `°` in the alt string and the src image is missing, WKWebView renders it as `Â°`.

**Comment by stephent** [comment]
And indeed, it's fixed by remembering to include `.meta(contentType: MediaType.html)`. Thanks again!
