### ISSUE TITLE
Preserve tabs

### ISSUE THREAD

**Issue by BryanJBryce** [pointfreeco/swift-html#58]
If I have a string like this:

`let note = "I love tacos.\n\n\tI love every kind of taco."`

and I use it for the text in a paragraph, the element preserves the new lines, but tab is lost.

Is there something I can do to fix this?

**Comment by BryanJBryce** [comment]
The answer is, "no, that's exactly how HTML works." 🤦‍♂

**Comment by mbrandonw** [comment]
Sorry we lost track of this, but glad you found what you needed!
