### ISSUE TITLE
Constructing lists dynamically

### ISSUE THREAD

**Issue by truemetal** [pointfreeco/swift-html#67]
I'm probably missing out something, but is it possible to add `.li` dynamically to `.ul`?
The following does not seem to work:

```swift
var list = Node.ul()
list.append(.li("Item"))
```

Cheers

**Comment by mbrandonw** [comment]
Hey @truemetal, there are a few ways.

For one, if the list of `li`s can be derived from another collection, then you can simply `map` on the collection and embed it in a `fragment` node:

```swift
Node.ul(
  .fragment(
    [1, 2, 3]
      .map { .li(.text("Item \($0)")) }
  )
)
```

If you need to build the list in a more imperative fashion, like using the `appending` method, then you need construct an array of `ChildOf<Tag.Ul>`. This type expresses the types of nodes that are capable of being a child in the `<ul>` elements, such as `li`s:

```swift
var children: [ChildOf<Tag.Ul>] = []

children.append(.li("Item 1"))
children.append(.li("Item 2"))
children.append(.li("Item 3"))

Node.ul(.fragment(children))
```

Hope that helps!

**Comment by truemetal** [comment]
@mbrandonw this definitely helps, thanks!
