### ISSUE TITLE
Adding Html as a dependency results in error.

### ISSUE THREAD

**Issue by JaapWijnen** [pointfreeco/swift-html#72]
When I add the swift-html package as a dependency I get the following error: 
`product dependency 'Html' in package 'swift-html' not found` 
Not sure what to do here, have the feeling it has to do with tools versioning could that be? 

package dependency looks as follows: 
`.package(url: "https://github.com/pointfreeco/swift-html.git", from: "0.3.1"),`
target dependency: (needed for 5.2)
`.product(name: "Html", package: "swift-html"),`

**Comment by stephencelis** [comment]
SPM changed their conventions with 5.2+, which makes things a lil confusing. The `swift-html` package is named `Html`, so I think you need to specify the product and package to be the same here:

```swift
.product(name: "Html", package: "Html"),
```

I _think_ that should get things working, though you may also need to add `name` to the `package` directive.

We should really change things, though, in the future to use `swift-html` as the package name.

**Comment by JaapWijnen** [comment]
I was using that, but got it working by also adding a name property to the package dependency itself:
`.package(name: "Html", url: "https://github.com/etc", from: "0.3.1")` 
Might be worth adding to the readme! (the name addition wouldn't be necessary if the package name and gh url slug match, so `name: "swift-html") 
I was trying to use Html with vapor 4, got it working so I'll make a PR with an example of the above in a minute (on the swift-html-vapor repo) :)

**Comment by JaapWijnen** [comment]
I only just realised that this is exactly what you're describing in the last two lines of your response, apologies 😅
