### ISSUE TITLE
srcset init() should sort by "size"

### ISSUE THREAD

**Issue by djstevenson** [pointfreeco/swift-html#75]
When a 'srcset' attribute is converted from a dictionary to a string, the ordering should be fixed, e.g. sort by size.description ?

Without this:

 * Every time I render my output, the arbitrary order changes, and, as I commit my output to git, I have a load of commits that are just making unnecessary changes to the order of the resolutions in the srcsets. It messes up my git history.
 * I'm hoping to adopt snapshot testing, and it's going to break that too.

**Comment by djstevenson** [comment]
I'm planning to submit a PR, in case you agree this is a useful idea.

**Comment by djstevenson** [comment]
A PR does not seem possible, as there is a file missing (Render.swift) that causes build failures.

**Comment by djstevenson** [comment]
PR #76 refers

There are CI build fails, but these appear unrelated to my requested changes.

**Comment by djstevenson** [comment]
Is there anything else I need to do to get this considered for inclusion?

If it's no good let me know, I'll stick with using a fork. 

Thanks.

**Comment by djstevenson** [comment]
Is this project abandoned?

**Comment by mbrandonw** [comment]
Hi there, the project is definitely not abandoned. It powers our entire site pointfree.co!

However, maintaining all of our open source can be quite time consuming. We tend to prioritize PR's that make changes that can't be made from the outside. In this case it's possible to vend a version of `srcset` that does the sorting, albeit it would have to be a different name.

We'll try to take a look at your PR tomorrow! Cheers

**Comment by djstevenson** [comment]
Great, thanks! I didn't mean to sound impatient :)

I'm currently using SwiftPM to refer to my fork.

**Comment by stephencelis** [comment]
Got around to merging #76, (finally, I know!). Thanks!
