### ISSUE TITLE
Could not find module & "unexclaim" sample issue

### ISSUE THREAD

**Issue by phr85** [pointfreeco/swift-html#85]
Hi everyone
I try to use swift-html in my project.

Currently I have two Issues:

1. On my Mac M1, when I try to build App I get following error:
"Could not find module 'Html' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at:"
![Screenshot 2022-02-10 at 15 55 17](https://user-images.githubusercontent.com/1322091/153433392-4fd584b5-2ff0-4c6f-a3b3-1a058efb1bd8.png)

2. I try to use sample function unexclaim() from readme.
But I get this Issue:
![Screenshot 2022-02-10 at 15 56 42](https://user-images.githubusercontent.com/1322091/153433682-27a75812-aaa7-428e-9b61-0cc681644b93.png)

Maybe someone has hint for me?

Bests from Swiss Mountains

Philippe

**Comment by mbrandonw** [comment]
Hi @phr85, thanks for bringing this up. I just opened a PR #86 to fix the `unexclaim` function.

I can't reproduce the other error you are having. Do you have some more details of how you are trying to use the package? Is this error from the integration with your project, or is it happening when opening this package directly?

**Comment by phr85** [comment]
Hi @mbrandonw  Thank you for fast fix of function.
I reverted everything and reinstall again Package. Now everything is working well.
Bests Philippe
