### ISSUE TITLE
Use of elements not in the library

### ISSUE THREAD

**Issue by Bjorninn1** [pointfreeco/swift-html#90]
Hello, I have been able to make some examples work using the library but how would I add an element to the body that's not in the swift-html library? For example if a script is used and it gives access to some new element that's not a ".h1", ".p", ".div" etc. how would that be done? Would really appreciate any suggestions to solve this, thank you.

**Comment by stephencelis** [comment]
@Bjorninn1 Check out the "design" section of the README, which shows how helpers are just sugar over the raw values:

https://github.com/pointfreeco/swift-html#design
