### ISSUE TITLE
Inside <dl>, wrapping <dd>, <dt> elements inside <div> doesn't seem to work

### ISSUE THREAD

**Issue by nkalvi** [pointfreeco/swift-html#94]
From quick help for `dl`:
>  Each term-description group consists of one or more terms (represented by `<dt>` elements) possibly as children of a `<div>` element child, and one or more descriptions (represented by `<dd>` elements possibly as children of a `<div>` element child), ignoring any nodes other than `<dt>` and `<dd> `element children, and `<dt>` and `<dd>` elements that are children of `<div>` element children within a single `<dl>` element.

But, trying the following causes compiler error `Type 'ChildOf<Tag.Dl>' has no member 'div'`

```swift
      .dl(
        .div(
            .dt("term"),
            .dd("description")
        )
      )
```

**Comment by mbrandonw** [comment]
Good catch! Would you be willing to open a PR to fix this? You can extend `ChildOf<Tag.Dl>` to add a `static func div`.

**Comment by nkalvi** [comment]
Thank you - I'll submit request.
