### ISSUE TITLE
Update to use actions/checkout@v3?

### ISSUE THREAD

**Issue by nkalvi** [pointfreeco/swift-html#97]
https://github.com/pointfreeco/swift-html/blob/789c2676e31e90feee49c490fdbd9e796aebeed5/.github/workflows/ci.yml#L28

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by mbrandonw** [comment]
Hi @nkalvi, do you want to open a PR to update that?
